---
title: "ClassNotesLoops"
author: "Holly Westbrook"
date: "2/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

real loop hours

for(how many times you want to repeat){
    code you want to repeat
}
i is an iterand
```{r}
#different ways to tell R to count from 1 to 4
c(1:4)
seq(1,4)
seq(from=1, to=4)

for(i in c(1:4)){
  print()  
}

for(counter in c(1:4)){
  print(paste("my counter is", counter))
}

my_vector = c(1,3,5,7,9)
n = length(my_vector)
#let's say we want to square every number in the vector
my_squared_vector = rep(NA, n) #fill with NA n times to make them the same length
for (i in seq(from = 1, to = n)){
  my_squared_vector[i] = my_vector[i]^2
}
my_squared_vector
```

add numbers in vec
```{r}
vec = c(1,3,5,7,9)
total = 0

for(i in seq(length(vec))){
  total = total + vec[i]
  print(total)
}


```


### Exercise 5.1

Use a for() loop to calculate the factorial (symbol !) of any integer number greater than 0. (For example: 3! = 3*2*1 = 6) Test it with `num = 3` and `num = 6`.

```{r}
num = 6

for (i in num){
 print(factorial(num))
}


```

nested loops

```{r}
mat = matrix(c(2,0,8,3,5,-4), nrow=2, ncol=3)
mat
results = matrix(data=NA, nrow=2, ncol=3)

for (i in c(1:2)){
  for(j in c(1:3)){
    results[i,j] = mat[i,j]^2
  }
}
results


```

while loops

```{r}
num = -3
while(num<0){
  num = num+1
  print(num)
}
num



```





